--MERGE IN SQL Server--
MERGE INTO StudentTarget AS T
USING StudentSource AS S
ON T.ID = S.ID
WHEN MATCHED THEN
     UPDATE SET T.NAME = S.NAME
WHEN NOT MATCHED BY TARGET THEN
     INSERT (ID, NAME) VALUES (S.ID, S.NAME)
WHEN NOT MATCHED BY SOURCE THEN
     DELETE;

